/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Bunny.gltf -o app/components/three/Bunny.tsx -r public 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { bunnyState, senarioState } from "./BunnyStates";
import { useRecoilState } from "recoil";

type GLTFResult = {
  nodes: {
    Pyramid: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
  };
};
export function Bunny(props: any) {
  const [state, setState] = useRecoilState(bunnyState);
  const [senario, setSenario] = useRecoilState(senarioState);

  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/Bunny.gltf"
  ) as GLTFResult;

  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // default movement
    if (state === "default") {
      actions["Idle"]?.reset().fadeIn(0.5).play();
      return () => actions["Idle"]?.fadeOut(0.5);
    }
    // say Hi when it clicked
    if (state === "greeting") {
      actions["Idle"]?.reset().fadeIn(0.5).stop();
      actions["Wave"]?.reset().fadeIn(0.5).play();

      if (senario === "Intro") setSenario("Greeting");

      setTimeout(() => {
        actions["Wave"]?.reset().fadeOut(0.5).stop();
        setState("default");
      }, 1500);
      return () => actions["Wave"]?.fadeOut(0.5);
    }
  }, [state]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={(e) => setState("greeting")}
    >
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Bunny">
            <skinnedMesh
              name="Cube074"
              geometry={nodes.Cube074.geometry}
              material={materials.Bunny_Main}
              skeleton={nodes.Cube074.skeleton}
            />
            <skinnedMesh
              name="Cube074_1"
              geometry={nodes.Cube074_1.geometry}
              material={materials.Bunny_Secondary}
              skeleton={nodes.Cube074_1.skeleton}
            />
            <skinnedMesh
              name="Cube074_2"
              geometry={nodes.Cube074_2.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Cube074_2.skeleton}
            />
            <skinnedMesh
              name="Cube074_3"
              geometry={nodes.Cube074_3.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Cube074_3.skeleton}
            />
          </group>
          <group name="Carrot">
            <skinnedMesh
              name="Cube077"
              geometry={nodes.Cube077.geometry}
              material={materials["Material.024"]}
              skeleton={nodes.Cube077.skeleton}
            />
            <skinnedMesh
              name="Cube077_1"
              geometry={nodes.Cube077_1.geometry}
              material={materials["Material.011"]}
              skeleton={nodes.Cube077_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Bunny.gltf");
